[www]
php_admin_value[max_file_uploads] = 300
php_admin_value[max_input_vars] = 5000
; nginx is set to 100M so that's the real cap
php_admin_value[post_max_size] = 128M
php_admin_value[upload_max_filesize] = 20M
